services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=jbooks'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'